### ISSUE TITLE
GetUserIdFromUserNameAsync error

### ISSUE THREAD

**Issue by anomjohn12** [tidusjar/Threads.Api#2]
After your last update, features such as logging in, following, unfollowing are working fine, but **GetUserIdFromUserNameAsync** function gives the following error.

> '"utf-8"' is not a supported encoding name. See the documentation for the Encoding.RegisterProvider method for information on defining a custom encoding.
Parameter name: name

I manually enter the user ids and the functions work fine.

do you have this problem? Is there a function I should check? and can you add the following as a feature

- like
- undelete likes
- get follower list

**Comment by tidusjar** [comment]
Can you please provide example code to reproduce the issue?

regarding new apis. I am working on adding them

**Comment by anomjohn12** [comment]
In the 1st and 2nd picture, I changed the relevant parts to string and sent the user id manually and it worked fine, but when I want to use **GetUserIdFromUserNameAsync**, it gives an error as in the 3rd picture.

### img1
[https://i.imgur.com/PsXyaVr.png](https://i.imgur.com/PsXyaVr.png)
### img2
[https://i.imgur.com/hIC7Vly.png](https://i.imgur.com/hIC7Vly.png)
### img3
[https://i.imgur.com/XSmMBo0.png](https://i.imgur.com/XSmMBo0.png)

error in picture 3

> System.InvalidOperationException: The character set provided in 'ContentType' is invalid. Content using an invalid character set cannot be read as a string.'

> ArgumentException: '"utf-8"' is not a supported encoding name. See the documentation for the Encoding.RegisterProvider method for information on defining a custom encoding.
Parameter name: name

**Comment by tidusjar** [comment]
Try using the Nuget package that’s being published.
