### ISSUE TITLE
Can't login threads api, Threads have changed the authentication mechanism

### ISSUE THREAD

**Issue by wishmee** [tidusjar/Threads.Api#4]
https://i.instagram.com/api/v1/bloks/apps/com.bloks.www.bloks.caa.login.async.send_login_request/

result :
`{"layout":{"bloks_payload":{"data":[],"props":[{"id":"-6917714003241327602","name":"ttrc_instance_id"},{"id":"2231046902902122168","name":"override_login_success_action"}],"error_attribution":{"logging_id":"{\"callsite\":\"{\\\"product\\\":\\\"bloks_caa_login\\\",\\\"feature\\\":\\\"com.bloks.www.bloks.caa.login.async.send_login_request\\\",\\\"integration\\\":\\\"bloks_screen\\\",\\\"oncall\\\":\\\"caa_login\\\"}\",\"push_phase\":\"C3\",\"version\":1,\"request_id\":\"Aw8S2rvIkpAnkIKLo5XF6Za\"}"},"tree":{"㐟":{"#":" (bk.action.core.TakeLast, (ig.action.cdsdialog.OpenDialog, (bk.action.tree.Make, (bk.action.i32.Const, 13799), (bk.action.i32.Const, 40), \"Unable to log in\", (bk.action.i32.Const, 35), \"An unexpected error occurred. Please try logging in again.\", (bk.action.i32.Const, 36), (bk.action.tree.Make, (bk.action.i32.Const, 13800), (bk.action.i32.Const, 36), \"OK\", (bk.action.i32.Const, 35), (bk.action.core.FuncConst, (bk.action.logging.LogEvent, \"caa_login_client_events_ig\", \"\", (bk.action.map.Make, (bk.action.array.Make, \"core\", \"login_params\"), (bk.action.array.Make, (bk.action.map.Make, (bk.action.array.Make, \"event\", \"event_category\", \"event_flow\", \"event_request_id\", \"event_step\", \"is_dark_mode\", \"exception_code\", \"exception_message\", \"exception_type\", \"extra_client_data\", \"logged_out_identifier\", \"logged_in_identifier\", \"waterfall_id\"), (bk.action.array.Make, \"login_error_dialog_ok_clicked\", \"login_home_page_interaction\", \"login_manual\", \"6ad13371-dd93-41b2-9636-c5357946dfa3\", \"home_page\", (ig.action.IsDarkModeEnabled), (bk.action.i32.Const, 0), \"\", \"\", (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make)), \"\", \"\", \"7e8ccada-d140-44b5-b583-7ef54a58a11c\")), (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make))))))), (bk.action.i32.Const, 42), (bk.action.i32.Const, 0)), (bk.action.tree.Make, (bk.action.i32.Const, 13808))), (bk.action.map.Make, (bk.action.array.Make, \"should_dismiss_loading\"), (bk.action.array.Make, (bk.action.bool.Const, true))))"}}}},"status":"ok"}`

Previously it was very smooth to log in and make a post with API, but now I can't log in using the API even though the data/param is correct and there is no problem in the Instagram account :(

**Comment by tidusjar** [comment]
Looks like they have blocked or changed the authentication mechanism

**Comment by tidusjar** [comment]
Nuget 1.2.0-alpha released that now fixes this. use the new `LoginAsync` method
